### ISSUE TITLE
Pinouts

### ISSUE THREAD

**Issue by F0RSV1NNA** [terrafirma2021/ESP32s3_KMBOX#1]
Would love to see a pinout, or a photo of both sides for soldering!
 amazing project going to test it out once my dev boards arrive.

**Comment by F0RSV1NNA** [comment]
also, should i be soldering the boards together before flashing or after flashing & which ports do i use to flash? 
i know these probably seem like dumb questions but would be very helpful as a beginner in platformIO

**Comment by terrafirma2021** [comment]
HI, Thanks for taking the time to try my project!
Sorry for not attaching the PCB design and pinouts!

I have updated my readme now, if you need any advice be sure to let me know.

Good luck with your project :)

**Comment by terrafirma2021** [comment]
Regarding soldering vs flashing, I would advise to just flash a standard hello world CPP to your boards, just to ensure that they do function first.

But once you are happy then sure solder away then you can flash again without issues, having the pins connected before the code in this case is not a problem :).

Cheers 


(I will close this for now, if you need any help feel free to reopen and i will assist)

**Comment by terrafirma2021** [comment]
https://github.com/terrafirma2021/ESP32s3_KMBOX/blob/main/Photos/pcb_design.png


Designs added and updated, thanks!

**Comment by F0RSV1NNA** [comment]
> https://github.com/terrafirma2021/ESP32s3_KMBOX/blob/main/Photos/pcb_design.png
> 
> Designs added and updated, thanks!


https://github.com/terrafirma2021/ESP32s3_KMBOX/assets/137400069/c34ac423-2fa3-49a3-8681-16719b8afe11


Accidentality ordered n8r2's but my n16r8's came in today! and i've got it working without an issue!! Amazing project which im learning alot about esp32s because of. thank you for this amazing project absolutely sniffing around your other projects now for my MT-10 when im feeling more confident.
