### ISSUE TITLE
Usb C to Usb A adapter 

### ISSUE THREAD

**Issue by TheCloneOp** [terrafirma2021/ESP32s3_KMBOX#2]
I built the board and flashed the firmware onto it and tested it using wasd and it moved my mouse but I cant get any power to go my mouse for me to try and move my mouse while the device is plugged in

**Comment by terrafirma2021** [comment]
Hi, can you enable 
build_flags = -DCORE_DEBUG_LEVEL=5
on your bottom esp and submit a debug for me please

**Comment by TheCloneOp** [comment]
I'm very new to visual code when do I go to enable that

**Comment by terrafirma2021** [comment]
![image](https://github.com/terrafirma2021/ESP32s3_KMBOX/assets/69117226/91adce40-9947-4626-a7e7-24e59d390d7a)
it is here sir

**Comment by TheCloneOp** [comment]
![image](https://github.com/terrafirma2021/ESP32s3_KMBOX/assets/175193022/0458da62-886f-4ac8-98bf-a1249b24cd03)
like so?

**Comment by terrafirma2021** [comment]
yes sir then build and send a debug log please

**Comment by TheCloneOp** [comment]
![image](https://github.com/terrafirma2021/ESP32s3_KMBOX/assets/175193022/071f7e1d-3459-4886-83a7-9533cab84d09)
Sorry just want to make sure first day ever using this. Do I click this

**Comment by terrafirma2021** [comment]
![image](https://github.com/terrafirma2021/ESP32s3_KMBOX/assets/69117226/f3be166c-6f4a-47da-b727-c2bbd2c6be6e)

**Comment by TheCloneOp** [comment]
ok I did that how do I send a debug log now?

**Comment by terrafirma2021** [comment]
yes please

the debug is handled via serial

**Comment by TheCloneOp** [comment]
I suppose I should rephrase what do I need to go to and click to that and if discord would be easier I can screen share, Im a complete noob

**Comment by terrafirma2021** [comment]
https://github.com/terrafirma2021/ESP32s3_KMBOX/blob/main/Test_Script/logger.py

Here I added my serial tool for you to upload the log file, keep all chat to my repo because it will help others, thus its important to assist others who may have the same issue 

Run the py in a folder and it will create a log file for you, 
then just append the log here.

make sure that your baud rate matches 

Serial0.begin(230400);

**Comment by TheCloneOp** [comment]
![image](https://github.com/terrafirma2021/ESP32s3_KMBOX/assets/175193022/45f7b21c-8b16-4a2d-82a7-96e005c5881e)
like so and press 1?

**Comment by terrafirma2021** [comment]
You don't need to run it from vscode


just run the py by double clicking, it will handle the log for you, you will have the txt file in the same folder as the py

**Comment by terrafirma2021** [comment]
the txt file will be created if it does not exist, and it will append to the txt file if it does :)

**Comment by TheCloneOp** [comment]
[log.txt](https://github.com/user-attachments/files/16171519/log.txt)

**Comment by TheCloneOp** [comment]
I think I did it right

**Comment by terrafirma2021** [comment]
yes, now plug in the mouse and remove to see if the callback triggers whilst the serial is connected

**Comment by TheCloneOp** [comment]
I plugged mouse in and it didnt work not following you on this "see if the callback triggers whilst the serial is connected" my discord is thecloneop could you add me so I can screen share for you bc I think I did it wrong

**Comment by terrafirma2021** [comment]
sure

**Comment by terrafirma2021** [comment]
Thanks for the time to help with my code, the issue ended up being a bad board, 

Referenced here also:
<a href="https://github.com/espressif/esp-idf/issues/11456">Issue #11456</a>

![error](https://github.com/user-attachments/assets/bd4ebcc6-14aa-4cbc-aac0-e436a99dc2cc)
Closing issue.
