### ISSUE TITLE
Strange Power Behavior

### ISSUE THREAD

**Issue by F0RSV1NNA** [terrafirma2021/ESP32s3_KMBOX#3]
Noticed this just now after getting mine fully soldered and working earlier today.

it appears on my logitech g502x (USB-C to USB-C) and G pro wireless (micro-b to USB-C adapter) mouses

while plugged in they have no on board DPI control like they typically would even when "disconnected" from a PC. 

as-well the battery's both drained INSANELY fast. 
which is weird since they are hardwired straight from the esp32 device and would be provided power to "charge"/run off
they will both eventually drain the battery fully (an hour maybe longer) and turn off completely as if unplugged. 

Just theorizing but maybe something to do with configurationDescriptor_MaxPower if the mouse is also reading that some how? and thinking its fully charged or wrong value so = no charge request. 
 
 just got it up and running a few hours ago going to attempt tweaking with it later but its bed time for right now while the mice recharge 
 and will actually try changing the hardcoded values in USBSetup.h to match one of my mice once i learn how to dump it FULLY.

Also thanks again for this amazing project, and the support your giving to those who are inexperienced.

**Comment by terrafirma2021** [comment]
HI, thanks for the feedback. The way USB works is the host will poll the mouse, and the mouse will tell the host if we have data to handle or not, my approach did not take into account the needs of battery saving on the wireless mouse. So it will be polling your mouse at 1000hz until the battery dies, It's simple to solve using a reduced poll rate and when the mouse responds with data it will wake up to max poll rate until some idle time and the sleep will kick in. I will look how windows handles the timing for this and include this method for you.

**Comment by terrafirma2021** [comment]
I will leave this open until I update the method

**Comment by terrafirma2021** [comment]
![image](https://github.com/user-attachments/assets/44f9faf1-74b8-47fc-92fa-acd9628fd060)
I have updated and enabled remote wakeup for you, i will push another update soon

**Comment by terrafirma2021** [comment]
Closing the issue as i have produced a fix, If there is any issue, let me know. Thanks
